02_urban_change: r'\\GOST-CIFS\gost-cifs\GLOBAL\POP&DEMO\02_urban_change\'
03_Africa_20m_landcover: '\\GOST-CIFS\gost-cifs\GLOBAL\LCVR\03_Africa_20m_landcover\'
03_landcover: '\\GOST-CIFS\gost-cifs\GLOBAL\LCVR\03_landcover\'
07_air_quality: '\\GOST-CIFS\gost-cifs\GLOBAL\HAZD\Air_Pollution\07_air_quality\'
11_landslides: '\\GOST-CIFS\gost-cifs\GLOBAL\HAZD\Landslides\11_landslides\'
