02_urban_change: '../global_data_sets/02_urban_change/GHS_BUILT_LDSMT_GLOBE_R2018A_3857_30_V2_0/V2-0/'
07_air_quality: '../global_data_sets/07_air_quality/'
11_landslides: '../global_data_sets/11_landslides/'
